### ISSUE TITLE
Usage examples/nits

### ISSUE THREAD

**Issue by oom-is** [thess/mfstools#1]
I understand the "auto-login as user **tivo**; preface commands with **root** to run them as `sudo -s`" theory.

In practice, though, it means that folks who haven't used mfstools recently need some documentation hints.
Examples:

To find what drive letters were assigned for SCSI/SATA disks:
  `root fdisk -l | grep "sd"`

To perform a normal mfscopy with source drive /dev/sda and destination drive sdb:
  `root mfscopy -a /dev/sda /dev/sdb`

Attempting the second command as user tivo/without sudo results in an error:
  "Copy source: /dev/sda10: Permission denied"
...which could be surprising to folks who try to use the tivocommunity forum thread (which assumes mfstools running as root) as their documentation.

**Comment by thess** [comment]
Thanks for the feedback.

It was never my intent to have the **root** alias used as a command prefix. The `-s` option launches another shell in which the command may not behave then same as it would if invoked interactively. Use **root** alias alone to open a new shell and execute commands therein. If you only want to invoke a single command, use `sudo <command-line>` form without the `-s` option.

I will update the documentation to point this out better. Additionally, it might make sense to add a check if you are running as **root** to the utilities and issue a warning that you should invoke them as **root** -- Or, it might be good enough to install the utilities with the SUID owner set. However, as you pointed out by the `fdisk -l` command that may not be enough.

**Comment by jmbach** [comment]
I think an easier way to identify the drives would be using lsblk -o name,size,vendor rather than fdisk.  For me the output is cleaner and easier to understand. 

A check for root prior to running the commands would be ideal along with a blurb to indicate how to run it as root if it is not ran as root.

**Comment by thess** [comment]
Yes, I always use **lsblk** to find plugged in drives. The opts you mention are a good way to go -- will document as well as adding root check to utils as necessary.

**Comment by oom-is** [comment]
Well, that's sort of funny - I've been using sudo so long (Evi Nemeth book) and in some oddly-paranoid environments that I didn't even question what sudo -s was supposed to do - I was just looking for a command prefix that would work for each individual command while running as a non-priv user.  Thanks for the explanation as that does make sense.  (You note that you'll update the documentation, but apparently the pointer to that documentation needs to be larger, neon, and flashing as this luser missed it entirely...)

Also mildly funny: the `fdisk - l | grep "sd"` was from a tivocommunity post by... @jmbach .  I'm so old-school I usually do `dmesg |grep -10` sd ...

Regardless, I can report success expanding a 1TB TiVo "Bolt" original drive onto a 4TB 3.5" disk in an external enclosure.
There was much rejoicing, and many thanks to both of you two.
