### ISSUE TITLE
Error in mfsaddfix

### ISSUE THREAD

**Issue by jmbach** [thess/mfstools#3]
A couple of people who have been trying to expand their images had run into an error when running mfsaddfix.  Looking at the code, the error is introduces at line 442.  The variable s was used to denote what partition the added partition was moved to.  When it was used for the read command for error handling, the value was lost and subsequently the following case command failed.  Looks like the other apm utilities had similar changes but I have not evaluated to see if it introduces problems.

**Comment by jmbach** [comment]
I think we need to look at all the error handling changes in the apmutils and consider standardizing error handling variables to variables not found in the original code.  Suggestion would be rr for read, ww for write, etc.  It might be easier than trying to examine the code to see if already used variables are being modified prior to being needed again later in the code.

**Comment by jmbach** [comment]
I do have a proposed changes but am unable to upload it.

**Comment by thess** [comment]
If you want to submit a PR to fix this issue, just fork the repo, branch and create a pull-request. If interested, I can also make you a member of this repo so you can merge changes yourself. Let me know if I can help.

ITMT - I'll look over the code you mentioned.

**Comment by jmbach** [comment]
I forked it, made the changes, and requested a pull.

**Comment by thess** [comment]
Merged #4 manually (a85c0ce), created new v3.34-3 package release. Assets on-the-way.
Thanks for this.
